 Step 1 — What is Feature Scaling?
- Definition: Adjusting the range of features so they are on a similar scale.
- Why: Some models (like Logistic Regression, SVM, KNN) are sensitive to feature magnitude.
- Layman analogy: Imagine a race where one runner measures distance in meters and another in kilometers. Without scaling, the kilometer runner looks much faster. Scaling ensures everyone runs on the same track.

 Step 2 — Methods of Feature Scaling
- Normalization (Min‑Max Scaling):
- Scales values between 0 and 1.
- Formula:
X'=\frac{X-X_{min}}{X_{max}-X_{min}}- Standardization (Z‑Score Scaling):
- Centers data around mean = 0, standard deviation = 1.
- Formula:
X'=\frac{X-\mu }{\sigma }

In [1]:
# Step 3
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Load dataset
iris = load_iris()
X = iris.data   # features (petal length, width, etc.)

# Min-Max Scaling (Normalization)
minmax_scaler = MinMaxScaler()
X_minmax = minmax_scaler.fit_transform(X)
print("First 5 rows after Min-Max Scaling:\n", X_minmax[:5])

# Standardization (Z-Score Scaling)
std_scaler = StandardScaler()
X_std = std_scaler.fit_transform(X)
print("\nFirst 5 rows after Standardization:\n", X_std[:5])

First 5 rows after Min-Max Scaling:
 [[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]

First 5 rows after Standardization:
 [[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]
