In [1]:
# Day 9: NumPy Arrays Basics

import numpy as np   # np is the short name for NumPy

In [2]:
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Create a 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
print("Shape of arr1:", arr1.shape)   # (5,) → 5 elements
print("Shape of arr2:", arr2.shape)   # (2,3) → 2 rows, 3 columns

print("Data type of arr1:", arr1.dtype)   # int

Shape of arr1: (5,)
Shape of arr2: (2, 3)
Data type of arr1: int64


In [4]:
# Array of zeros
zeros = np.zeros((2,3))
print("Zeros array:\n", zeros)

# Array of ones
ones = np.ones((3,3))
print("Ones array:\n", ones)

# Array with a range of numbers
range_arr = np.arange(1, 10)   # 1 to 9
print("Range array:", range_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range array: [1 2 3 4 5 6 7 8 9]
