In [3]:
import numpy as np

# Create a 1D array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)

# Reshape into 2 rows and 3 columns
reshaped = arr.reshape(2, 3)
print("Reshaped array (2x3):\n", reshaped)

# Reshape into 3 rows and 2 columns
reshaped2 = arr.reshape(3, 2)
print("Reshaped array (3x2):\n", reshaped2)

Original array: [1 2 3 4 5 6]
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
Reshaped array (3x2):
 [[1 2]
 [3 4]
 [5 6]]


In [4]:
# Create a 1D array
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)

# Slice from index 1 to 3 (20, 30, 40)
print("Slice 1 to 3:", arr[1:4])

# Slice with step (every 2nd element)
print("Every 2nd element:", arr[::2])

# 2D array slicing
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n", arr2d)

# Get first row
print("First row:", arr2d[0])

# Get first column
print("First column:", arr2d[:,0])

# Get sub-matrix (top-left 2x2)
print("Top-left 2x2:\n", arr2d[0:2, 0:2])

Original array: [10 20 30 40 50]
Slice 1 to 3: [20 30 40]
Every 2nd element: [10 30 50]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
First column: [1 4 7]
Top-left 2x2:
 [[1 2]
 [4 5]]
